baseURL = 'https://hugosteel.netlify.app'
languageCode = 'el'
paginate = 6
theme= "coHub"
title = 'SteelMade — Κουφώματα Αλουμινίου, Μεταλλικές κατασκευές'
 
[Menu]
[[menu.Main]]
  name = "Κατασκευές"
  url  = "#gallery"
  weight = 1
  [[menu.Main]]
  name = "Υπηρεσίες"
  url  = "#service"
  weight = 2
  [[menu.Main]]
  name = "Εταιρία"
  url= "/about/"
  weight = 5
  [[menu.Main]]
  name = "Projects"
  url= "/products/"
  weight = 6
  [[menu.Main]]
  name = "Επικοινωνία"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://steelmade.gr/\" target=\"_blank\">Steel made Constructions </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo-latest.png"
  footerlogo = "images/logo-latest.png"
  footerDescription = "Συστήματα Αλουμινίου και Μεταλλικές Κατασκευές Γιαπουτζής Ευθύμης"

  [params.address]
  address = "Τατοϊου 118, Αχαρνές 13672"
  email = "info@steelmade.gr"
  openingDesc = ""
  openingHours = ""
  phone = "+30 694 830 8716"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "38.093805"
  longitude = "23.775293"
  pinImage = "images/pin.png"

  # Social icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1

  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 2
  
  
